"""add role to users

Revision ID: 4b05f4777900
Revises: fa5a650f2a75
Create Date: 2026-08-12 22:52:56.217023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b05f4777900'
down_revision: Union[str, None] = 'fa5a650f2a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default agregado a mano: la tabla ya tiene filas, y NOT NULL sin
    # default falla contra ellas -- coincide con el default "student" del modelo.
    op.add_column(
        'users',
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='student'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
