"""add ai explanation cache, ai recommendation cache, streak freezes

Revision ID: 5d33ef74392f
Revises: c83b647818c9
Create Date: 2026-08-13 08:06:02.824075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d33ef74392f'
down_revision: Union[str, None] = 'c83b647818c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streak_freezes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_streak_freeze_user_date')
    )
    op.create_index(op.f('ix_streak_freezes_user_id'), 'streak_freezes', ['user_id'], unique=False)
    op.create_table('ai_explanation_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('student_answer', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'student_answer', name='uq_ai_cache_question_answer')
    )
    op.create_index(op.f('ix_ai_explanation_cache_question_id'), 'ai_explanation_cache', ['question_id'], unique=False)
    op.add_column('test_attempts', sa.Column('ai_recommendation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempts', 'ai_recommendation')
    op.drop_index(op.f('ix_ai_explanation_cache_question_id'), table_name='ai_explanation_cache')
    op.drop_table('ai_explanation_cache')
    op.drop_index(op.f('ix_streak_freezes_user_id'), table_name='streak_freezes')
    op.drop_table('streak_freezes')
    # ### end Alembic commands ###
