"""add answered_at to test_attempt_items

Revision ID: fa5a650f2a75
Revises: 95d864971bb3
Create Date: 2026-08-10 22:21:56.235432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa5a650f2a75'
down_revision: Union[str, None] = '95d864971bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempt_items', sa.Column('answered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempt_items', 'answered_at')
    # ### end Alembic commands ###
